/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
//#include "../modules/juce_audio_utils/gui/juce_AudioVisualiserComponent.h"
//#include "../modules/juce_audio_utils/juce_audio_utils.h"
#include "MeterComponent.h"
#include "WaveformComponent.h"

//==============================================================================
/**
*/
class DrumReplacerAudioProcessorEditor : public AudioProcessorEditor,
	private Button::Listener,
	private Slider::Listener,
	private Timer,
	private ChangeListener
{
public:
    DrumReplacerAudioProcessorEditor (DrumReplacerAudioProcessor&);
    ~DrumReplacerAudioProcessorEditor();

    //==============================================================================
	enum TransportState
	{
		Stopped,
		Starting,
		Playing,
		Stopping
	};

    void paint (Graphics&) override;
    void resized() override;

	void buttonClicked(Button* button) override;
	void sliderValueChanged(Slider* s);

	void openButtonClicked();
	void playButtonClicked();

	void timerCallback();

	void changeListenerCallback(ChangeBroadcaster *source);

	float zoom;
	float waveLen;

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
	
	DrumReplacerAudioProcessor& processor;

	TextButton openButton;
	TextButton playButton;

	ToggleButton filterButton;

	AudioFormatManager formatManager;

	Slider gain1, gainThru, threshSlider, recoverySlider, HPF, LPF, zoomSlider;

	MeterComponent meterL, meterR;

	WaveformComponent waveform1, triggerWave;

	LookAndFeel_V3 lookAndFeel;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (DrumReplacerAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
