/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "MeterComponent.h"


//==============================================================================
/**
*/
class JuceVibAudioProcessorEditor  : public AudioProcessorEditor, private ToggleButton::Listener, private Slider::Listener, private Timer
{
public:
    JuceVibAudioProcessorEditor (JuceVibAudioProcessor&);
    ~JuceVibAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;

	void buttonClicked(Button* b);

	void sliderValueChanged(Slider* s);

	void timerCallback();

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    JuceVibAudioProcessor& processor;

	Label freqLabel;
	Label depthLabel;
	Label bypassLabel;

	Slider fSlider, dSlider;

	ToggleButton bypassButton;

	MeterComponent meter;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (JuceVibAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
